### ISSUE TITLE
Question: gridatack to show multiple notebooks?

### ISSUE THREAD

**Issue by joseberlines** [voila-dashboards/voila-gridstack#126]
Is it possible tonise gridstack voila to render in every of the grids a diferent notebook? The idea would be to be able to le the user chose the size of every of the applications depending on circumstances.
Thx.

**Comment by hbcarlos** [comment]
Hey Jose, thanks for the question.

Voila-Gristack can only render cells from one notebook because it's just a new view for a  notebook. You could write all the applications in the same notebook and show only the cell that you want. Then, deploying Voilà with `voila path/to/notebook.ipynb --template=gridstack --VoilaConfiguration.resources='{“gridstack”: {“show_handles”: True}}'` your users would be able to move the different cells as they wish.

**Comment by joseberlines** [comment]
Thanks a lot. So you know of any example notebook which also uses ipyvuetify to render stuff in every of the cells? IN your answer you talk about cells. You mean notebook cells. i.e. every grid corresponds to a particular cell.

**Comment by hbcarlos** [comment]
Voila-Gridstack editor it's just another view for a Notebook. That means when you open Voila-Gridstack editor in JupyterLab, you are just opening the notebook with another view and the different items that you see in the grid (that you can move or resize) are just cells from your notebook. All the position information of these cells is saved on the Notebook's metadata.

When opening a Notebook with Voila-Gridstack editor for the first time, the editor adds all the information to the Notebook's metadata. Still, by default, every cell is marked as hidden that's why the editor is empty, and when you drag a cell from the notebook, the metadata is changed to mark this cell as visible, but you still working on the same notebook.

Suppose you want to use ipyvuetify with Voila-Gridstack. Just create a Notebook with the functionality you wish (using ipyvuetify widgets). Once it is done, open this notebook with the Voila-Gridstack editor and drag the cells you want to show from the normal view of the Notebook to the Voila-Gridstack editor to create the layout you wish. When you save it, this information would be placed in the Notebook.

The last step would be to use Voilá to render the notebook outside JupyterLab as a standalone app by running the command `voila path/to/notebook.ipynb --template=gridstack` or `voila path/to/notebook.ipynb --template=gridstack --VoilaConfiguration.resources='{“gridstack”: {“show_handles”: True}}'` if you want to be able to move and resize the cells with the Notebook deployed using Voilá. You should have in mind that when using the option `--VoilaConfiguration.resources='{“gridstack”: {“show_handles”: True}}'` on Voilá, the information of the layout is not saved so, every time you launch your Notebook, you'll see the layout you created using the JupyterLab extension Voila-Gridstack.

**Comment by joseberlines** [comment]
This is such a great explanation!!!
