### ISSUE TITLE
how can I save it, after I reconfigured template by using {show_handles : True} option.

### ISSUE THREAD

**Issue by jaaaaaang** [voila-dashboards/voila-gridstack#173]
hi 
I thank you for voila-gridstack !! 

to apply this for my task, I wander that after I edit template using show_handles :True option, how could I save it ?

**Comment by hbcarlos** [comment]
Hi @jaaaaaang! You can not save the notebook from Voila. If you want to edit and save the layout, you have to use the notebook or JupyterLab extension.

**Comment by hbcarlos** [comment]
Hi @jessefreitag.
Because you are not using the gridstack template, you are using voila with the default template.

Try adding the template like this:
`voila mynotebook.ipynb --template=gridstack --VoilaConfiguration.resources='{"gridstack": {"show_handles": True}}'`

Remember, if your goal is to rearrange your layout and store it in the notebook, you can not do it from voila. You need to use JupyterLab for that.
