### ISSUE TITLE
ValueError: No template sub-directory with name 'gridstack' found in the following paths:   

### ISSUE THREAD

**Issue by txnguyen2921** [voila-dashboards/voila-gridstack#47]
I encountered this error when running `voila --template=gridstack path_to_notebook.ipynb`. 

> ValueError: No template sub-directory with name 'gridstack' found in the following paths:
        /Users/txnguyen/Library/Jupyter/voila/templates
        /Users/txnguyen/opt/anaconda3/envs/workenv/share/jupyter/voila/templates
        /usr/local/share/jupyter/voila/templates
        /usr/share/jupyter/voila/templates

Can someone help me with this? Thanks!  btw, I'm using conda to install voila.

**Comment by jtpio** [comment]
Thanks @txnguyen2921.

There seems to be the same issue on `master` in a fresh conda environment.

**Comment by jtpio** [comment]
@txnguyen2921 this issue was closed automatically by #53.

> I'm using conda to install voila.

In retrospect, it might not be related to #53 as the error message was slightly different.

Would it be possible to check again with the latest `voila-gridstack` pre-release?

```
pip install --pre -U voila-gridstack
```

And re-open (or open a new issue) if the problem persists.

Thanks!

**Comment by txnguyen2921** [comment]
@jtpio It works like charm after I installed the pre-release. Thank you very much!

**Comment by jtpio** [comment]
Great, thanks @txnguyen2921 for checking!
